name: Publish Release Artifacts
on:
  push:
    tags:
      - '**'

env:
  NeosPath: "${{ github.workspace }}/Libs/current/"

jobs:
  release:
    if: github.repository == 'neos-modding-group/NeosModLoader'
    runs-on: ubuntu-latest
    steps:
      - name: checkout NML
        uses: actions/checkout@v3
      - name: setup build environment
        uses: neos-modding-group/neos-plugin-setup-action@master
      - name: lint
        run: dotnet format --verbosity detailed --verify-no-changes ./NeosModLoader.sln
      - name: build headed
        run: |
          dotnet build ./NeosModLoader.sln --configuration Release "-property:Headless=false;CopyToLibraries=false"
          mv ./NeosModLoader/bin/Release/net462/NeosModLoader.dll ./NeosModLoader.dll
      - name: build headless
        run: |
          dotnet build ./NeosModLoader.sln --configuration Release "-property:Headless=true;CopyToLibraries=false"
          mv ./NeosModLoader/bin/Release/net462/NeosModLoader.dll ./NeosModLoaderHeadless.dll
      - name: upload workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: NeosModLoader
          path: |
            ./NeosModLoader.dll
            ./NeosModLoaderHeadless.dll
          if-no-files-found: error
      - name: upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          draft: true # if creating a new release, make it a draft
          files: |
            ./NeosModLoader/bin/Release/net462/0Harmony.dll
            ./NeosModLoader.dll
            ./NeosModLoaderHeadless.dll
          fail_on_unmatched_files: true
