name: Publish Release Artifacts
on:
  push:
    tags:
      - '**'

env:
  NeosPath: "${{ github.workspace }}/Libs/current/"

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'neos-modding-group/NeosModLoader' # only run for pushes to tags
    runs-on: ubuntu-latest
    steps:
      - name: setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: checkout NML
        uses: actions/checkout@v3
      - name: checkout Neos libs
        uses: actions/checkout@v3
        with:
          repository: neos-modding-group/Reference-Assemblies
          path: Libs
          ssh-key: ${{ secrets.REFERENCE_ASSEMBLIES_AUTH }}
      - name: lint
        run: dotnet format --verbosity detailed --verify-no-changes ./NeosModLoader.sln
      - name: build headed
        run: dotnet build ./NeosModLoader.sln --configuration Release "-property:Headless=false;CopyToLibraries=true"
      - name: build headless
        run: dotnet build ./NeosModLoader.sln --configuration Release "-property:Headless=true;CopyToLibraries=true"
      - name: upload workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: NeosModLoader
          path: |
            ${{ github.workspace }}/Libs/current/Libraries/NeosModLoader.dll
            ${{ github.workspace }}/Libs/current/Libraries/NeosModLoaderHeadless.dll
          if-no-files-found: error
      - name: upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          draft: true # if creating a new release, make it a draft
          files: |
            ${{ github.workspace }}/Libs/current/Libraries/NeosModLoader.dll
            ${{ github.workspace }}/Libs/current/Libraries/NeosModLoaderHeadless.dll
          fail_on_unmatched_files: true
