on: [push, pull_request]

env:
  NeosPath: "${{ github.workspace }}/Libs/current/"

jobs:
  build:
    if: github.repository == 'neos-modding-group/NeosModLoader'
    runs-on: ubuntu-latest
    steps:
      - name: setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: checkout NML
        uses: actions/checkout@v3
      - name: checkout Neos libs
        uses: actions/checkout@v3
        with:
          repository: neos-modding-group/Reference-Assemblies
          path: Libs
          ssh-key: ${{ secrets.REFERENCE_ASSEMBLIES_AUTH }}
      - name: lint
        run: dotnet format --verbosity detailed --verify-no-changes ./NeosModLoader.sln
      - name: build headed
        run: dotnet build ./NeosModLoader.sln --configuration Release "-property:Headless=false;CopyToLibraries=true"
      - name: build headless
        if: github.ref == 'refs/heads/master'
        run: dotnet build ./NeosModLoader.sln --configuration Release "-property:Headless=true;CopyToLibraries=true"
      - name: upload workflow artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: NeosModLoader
          path: |
            ${{ github.workspace }}/Libs/current/Libraries/NeosModLoader.dll
            ${{ github.workspace }}/Libs/current/Libraries/NeosModLoaderHeadless.dll
          if-no-files-found: error
