name: Test & CI Build
on:
  push:
    branches:
      - '**'
  pull_request:

env:
  NeosPath: "${{ github.workspace }}/neos_install/"

jobs:
  build:
    if: github.repository == 'neos-modding-group/NeosModLoader'
    runs-on: ubuntu-latest
    steps:
      - name: checkout NML
        uses: actions/checkout@v3
      - name: setup build environment
        uses: neos-modding-group/neos-plugin-setup-action@master
      - name: lint
        run: dotnet format --verbosity detailed --verify-no-changes ./NeosModLoader.sln
      - name: build headed
        run: |
          dotnet build ./NeosModLoader.sln --configuration Release "-property:Headless=false;CopyToLibraries=false"
          mv ./NeosModLoader/bin/Release/net462/NeosModLoader.dll ./NeosModLoader.dll
      - name: build headless
        if: github.ref == 'refs/heads/master' # only build headless for master branch builds
        run: |
          dotnet build ./NeosModLoader.sln --configuration Release "-property:Headless=true;CopyToLibraries=false"
          mv ./NeosModLoader/bin/Release/net462/NeosModLoader.dll ./NeosModLoaderHeadless.dll
      - name: upload workflow artifacts
        if: github.ref == 'refs/heads/master' # only publish artifacts for master branch builds
        uses: actions/upload-artifact@v3
        with:
          name: NeosModLoader
          path: |
            ./NeosModLoader.dll
            ./NeosModLoaderHeadless.dll
          if-no-files-found: error
